dataset:
  - path: 'data/source/naive'
    task: 'naive'

processed:
  path: 'data/processed'
  vocab:
    min_frequency: 5

hyperparameter:
  batch_size:
    value: 32
    opt: 'b'

train:
  task: 'naive'
